version: "3.9"

services:
  user-service:
    build:
      context: ./user
    image: user-service-flask
    container_name: "user-service"
    environment:
      - FLASK_APP=app.py
    ports:
      - 5001:5001
    networks:
      - inetwork 

  payment-service:
    build:
      context: ./payment
    image: payment-service-flask
    container_name: "payment-service"
    environment:
      - FLASK_APP=app.py 
    ports:
      - 5002:5002
    networks:
      - inetwork 

  report-service:
    build:
      context: ./report
    image: report-service-flask
    container_name: "report-service"
    environment:
      - FLASK_APP=app.py 
    ports:
      - 5003:5003
    networks:
      - inetwork 

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: "nginx-service"
    restart: unless-stopped
    networks:
      - inetwork
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./log/nginx:/var/log/nginx

networks:
  inetwork:
    driver: bridge
